### PR TITLE
PRODCI-17 Refactor into modules

### PR DESCRIPTION
**Pull request by rnc**

### CODE REVIEW

**Comment by rnc** [comment]
retest this please

**Comment by rnc** [comment]
ok to test

**Comment by rnc** [comment]
ok to test

**Comment by rnc** [comment]
@ryanzhang @yongyang This is a first pass at splitting the code into business logic versus tests for the CI system

**Comment by yongyang** [comment]
As discussed, it's a good idea to split the codes to common and test parts.

**Comment by rnc** [comment]
retest this please

**Comment by rnc** [comment]
retest this please

**Pull request merged**
