### PR TITLE
Refactor test logic into Validator api

### PR DESCRIPTION
**Pull request by rnc**
@ryanzhang  @yongyang  A possible approach to use a more standardised api for the validators which the tests then use. API for populating filtering data (which should probably come from configuration) is not yet defined

### CODE REVIEW

**Comment by yongyang** [comment]
I saw there is a super class of Validator, which has a validate abstract method, need to be implement in the sub test class. This means the test class will has only one test method and must be named validator, since Junit has @Test annotation and it can have any test method, this may bring confuse.

**Comment by rnc** [comment]
@yongyang Currently we have junit as compile dependency rather than as a test dependency. There are pros and cons to splitting the logic so that it can be run by the ci tests in a standard way and verified (be it by mocking or whatever). 
The idea was that the validation code has a standard contract so that it is easy add new ones, verify it works as expected and use in the actual pvt integration ci test cases.

**Comment by ryanzhang** [comment]
I think to use "validator" or junit @test has its pros and cons as Nick said.
I think before we are considering using what test interface in harness, should we consider that how we going to provide the generic test to product?
Should we provide the generic testcase directly in harness, or in general, or even only an api level support for product generic testcase?
Should we have a design of pvt test framework  first?

**Comment by ryanzhang** [comment]
+1
After discussion this with Nick and Yang in bluejeans, it makes sense to abstract the logic in harness/ without depends on junit.
Wrap the testlogic into validator also seems fine to me.

**Pull request merged**
